import "../styles/globals.css";
import { useState, useEffect } from "react";
import Login from "./login";
import { auth, db } from "../firebase";
import { doc, serverTimestamp, setDoc } from "firebase/firestore";
import Head from "next/head";
import Sidebar from "../components/Sidebar";
import { RecoilRoot } from "recoil";
function MyApp({ Component, pageProps }) {
  const [user, setUser] = useState(null);
  useEffect(() => {
    auth.onAuthStateChanged(async (user) => {
      if (user) {
        try {
          setDoc(doc(db, "users", user.uid), {
            email: user.email,
            photoURL: user.photoURL,
            lastSeen: serverTimestamp(),
          });
        } catch (error) {
          console.error(error);
        }
      }
      setUser(user);
    });
  }, []);
  return user ? (
    <>
      <Head>
        <title>Whatsapp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecoilRoot>
        <main className="bg-[#0a1014] flex h-screen xl:px-10 xl:py-5">
          <Sidebar />
          <Component {...pageProps} />
        </main>
      </RecoilRoot>
    </>
  ) : (
    <Login />
  );
}

export default MyApp;
